#####################
# simpsons-quotes-api ----------------------------------------------
#####################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpsons-quotes-api-deployment
  namespace: simpsons-quotes-ns
  labels:
    app: simpsons-quotes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpsons-quotes-api
  template:
    metadata:
      labels:
        app: simpsons-quotes-api
    spec:
      containers:
      - name: simpsons-quotes-api
        image: <TODO>  
        env:
          - name: DB_HOST
            valueFrom: 
              secretKeyRef:
                name: simpsons-quotes-api-scrt
                key: DB_HOST
          - name: DB_PORT
            valueFrom: 
              secretKeyRef:
                name: simpsons-quotes-api-scrt
                key: DB_PORT
          - name: DB_USER
            valueFrom: 
              secretKeyRef:
                name: simpsons-quotes-api-scrt
                key: DB_USER
          - name: DB_PASS
            valueFrom: 
              secretKeyRef:
                name: simpsons-quotes-api-scrt
                key: DB_PASS
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: simpsons-quotes-api-svc
  namespace: simpsons-quotes-ns
spec:
  type: ClusterIP
  #type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: simpsons-quotes-api
---
apiVersion: v1
kind: Secret
metadata:
  name: simpsons-quotes-api-scrt
  namespace: simpsons-quotes-ns
type: Opaque
data:                          
  DB_HOST: c2ltcHNvbnMtcXVvdGVzLWRiLXN2Yw== #"simpsons-quotes-db-svc"
  DB_PORT: MzMwNg==                         #"3306"
  DB_USER: cm9vdA==                         #"root"
  DB_PASS: UGFzc3dvcmQxMjM=                 #"Password123"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simpsons-quotes-api-ingress
spec:
  rules:
  #- host: myserviceb.foo.org
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simpsons-quotes-api-svc
            port:
              number: 8000
  ingressClassName: nginx
---
#####################
# db JOB ----------------------------------------------
#####################

apiVersion: batch/v1
kind: Job
metadata:
  name: simpsons-quotes-db-job
spec:
  template:
    spec:
      containers:
      - name: simpsons-quotes-db-job
        image: <TODO>
        command: ["mysql", "-P 3306", "-h <IP_BD>", "-u root",  "-p ", "< alta_db.sql"]
        env:
          - name: DB_HOST
            valueFrom: 
              secretKeyRef:
                name: simpsons-quotes-api-scrt
                key: DB_HOST
          - name: DB_PORT
            valueFrom: 
              secretKeyRef:
                name: simpsons-quotes-api-scrt
                key: DB_PORT
          - name: DB_USER
            valueFrom: 
              secretKeyRef:
                name: simpsons-quotes-api-scrt
                key: DB_USER
          - name: DB_PASS
            valueFrom: 
              secretKeyRef:
                name: simpsons-quotes-api-scrt
                key: DB_PASS
      restartPolicy: Never
  backoffLimit: 4

---
#####################
# db ----------------------------------------------
#####################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpsons-quotes-db-deployment
  namespace: simpsons-quotes-ns
  labels:
    app: simpsons-quotes-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpsons-quotes-db
  template:
    metadata:
      labels:
        app: simpsons-quotes-db
    spec:
      containers:
      - name: simpsons-quotes-db
        image: <TODO>  
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: simpsons-quotes-api-scrt
                key: DB_PASS
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: simpsons-quotes-db-svc
  namespace: simpsons-quotes-ns
spec:
  type: ClusterIP
  #type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: simpsons-quotes-db